---
- name: Create the necessary database schema
  template:
        src: db_script.sh.j2
        dest: "/{{ backend_src_dir }}/db_script.sh"
        mode: '0755'

- name: excecute db script
  shell: sh "{{ backend_src_dir }}/db_script.sh"

- name: Populate database
  command: "node /{{ backend_src_dir }}/seeds.js"